#Build phase for ubuntu
FROM ubuntu:latest

#installation and update
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install net-tools -y
RUN apt-get install sudo -y
RUN apt-get install tree -y
RUN apt-get install openssh-server -y
RUN apt-get install cron -y
RUN apt-get install vim -y

#make folder
RUN mkdir -p /scripts

#run command when start
CMD service cron start && service ssh start && tail -f /dev/null
